# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Reza/Computer Architecture/Lab/first session/pin_assignment.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IF_0_0/design_1_IF_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_IF_0_0 || ORIG_REF_NAME==design_1_IF_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register_0_0/design_1_Register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register_0_0 || ORIG_REF_NAME==design_1_Register_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register_0_1/design_1_Register_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register_0_1 || ORIG_REF_NAME==design_1_Register_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_1/design_1_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_1 || ORIG_REF_NAME==design_1_xlconstant_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_1/design_1_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_1 || ORIG_REF_NAME==design_1_xlconstant_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register_0_4/design_1_Register_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register_0_4 || ORIG_REF_NAME==design_1_Register_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ControlUnit_0_0/design_1_ControlUnit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ControlUnit_0_0 || ORIG_REF_NAME==design_1_ControlUnit_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RegisterFile_0_0/design_1_RegisterFile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RegisterFile_0_0 || ORIG_REF_NAME==design_1_RegisterFile_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MUX4_0_0/design_1_MUX4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MUX4_0_0 || ORIG_REF_NAME==design_1_MUX4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register_1_0/design_1_Register_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register_1_0 || ORIG_REF_NAME==design_1_Register_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register_1_1/design_1_Register_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register_1_1 || ORIG_REF_NAME==design_1_Register_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_OR1_0_0/design_1_OR1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_OR1_0_0 || ORIG_REF_NAME==design_1_OR1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_0/design_1_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_0 || ORIG_REF_NAME==design_1_xlslice_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_1/design_1_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_1 || ORIG_REF_NAME==design_1_xlslice_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MUX9_0_0/design_1_MUX9_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MUX9_0_0 || ORIG_REF_NAME==design_1_MUX9_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_0/design_1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_0 || ORIG_REF_NAME==design_1_xlconstant_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_OR1_1_0/design_1_OR1_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_OR1_1_0 || ORIG_REF_NAME==design_1_OR1_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_4_0/design_1_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_4_0 || ORIG_REF_NAME==design_1_xlconstant_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_NOT1_0_0/design_1_NOT1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_NOT1_0_0 || ORIG_REF_NAME==design_1_NOT1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_5_0/design_1_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_0 || ORIG_REF_NAME==design_1_xlslice_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_NOT1_0_1/design_1_NOT1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_NOT1_0_1 || ORIG_REF_NAME==design_1_NOT1_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_6_0/design_1_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_6_0 || ORIG_REF_NAME==design_1_xlslice_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_6_1/design_1_xlslice_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_6_1 || ORIG_REF_NAME==design_1_xlslice_6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_6_2/design_1_xlslice_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_6_2 || ORIG_REF_NAME==design_1_xlslice_6_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Condition_Check_0_2/design_1_Condition_Check_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Condition_Check_0_2 || ORIG_REF_NAME==design_1_Condition_Check_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_0/design_1_xlconstant_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_0 || ORIG_REF_NAME==design_1_xlconstant_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_1/design_1_xlconstant_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_1 || ORIG_REF_NAME==design_1_xlconstant_6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_6_2/design_1_xlconstant_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_6_2 || ORIG_REF_NAME==design_1_xlconstant_6_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dist_mem_gen_0_0/design_1_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dist_mem_gen_0_0 || ORIG_REF_NAME==design_1_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register9_0_0/design_1_Register9_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register9_0_0 || ORIG_REF_NAME==design_1_Register9_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register13_0_0/design_1_Register13_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register13_0_0 || ORIG_REF_NAME==design_1_Register13_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_1_0/design_1_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_1_0 || ORIG_REF_NAME==design_1_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_9_0/design_1_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_9_0 || ORIG_REF_NAME==design_1_xlslice_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_9_1/design_1_xlslice_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_9_1 || ORIG_REF_NAME==design_1_xlslice_9_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_10_0/design_1_xlslice_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_10_0 || ORIG_REF_NAME==design_1_xlslice_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_10_1/design_1_xlslice_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_10_1 || ORIG_REF_NAME==design_1_xlslice_10_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register24_0_0/design_1_Register24_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register24_0_0 || ORIG_REF_NAME==design_1_Register24_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_13_0/design_1_xlslice_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_13_0 || ORIG_REF_NAME==design_1_xlslice_13_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register4_0_0/design_1_Register4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register4_0_0 || ORIG_REF_NAME==design_1_Register4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_OR1_2_0/design_1_OR1_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_OR1_2_0 || ORIG_REF_NAME==design_1_OR1_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_14_0/design_1_xlslice_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_14_0 || ORIG_REF_NAME==design_1_xlslice_14_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_14_1/design_1_xlslice_14_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_14_1 || ORIG_REF_NAME==design_1_xlslice_14_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Val2Genrate_0_0/design_1_Val2Genrate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Val2Genrate_0_0 || ORIG_REF_NAME==design_1_Val2Genrate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_16_0/design_1_xlslice_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_16_0 || ORIG_REF_NAME==design_1_xlslice_16_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sign_extend_0_0/design_1_sign_extend_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sign_extend_0_0 || ORIG_REF_NAME==design_1_sign_extend_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADDER_0_0/design_1_ADDER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ADDER_0_0 || ORIG_REF_NAME==design_1_ADDER_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_9_0/design_1_xlconstant_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_9_0 || ORIG_REF_NAME==design_1_xlconstant_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Status_Register_0_1/design_1_Status_Register_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Status_Register_0_1 || ORIG_REF_NAME==design_1_Status_Register_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_17_0/design_1_xlslice_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_17_0 || ORIG_REF_NAME==design_1_xlslice_17_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ALU_0_0/design_1_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ALU_0_0 || ORIG_REF_NAME==design_1_ALU_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_18_0/design_1_xlslice_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_18_0 || ORIG_REF_NAME==design_1_xlslice_18_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register1_0_0/design_1_Register1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register1_0_0 || ORIG_REF_NAME==design_1_Register1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_19_0/design_1_xlslice_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_19_0 || ORIG_REF_NAME==design_1_xlslice_19_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register3_0_0/design_1_Register3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register3_0_0 || ORIG_REF_NAME==design_1_Register3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register4_1_0/design_1_Register4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register4_1_0 || ORIG_REF_NAME==design_1_Register4_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register_2_0/design_1_Register_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register_2_0 || ORIG_REF_NAME==design_1_Register_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Register_2_1/design_1_Register_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Register_2_1 || ORIG_REF_NAME==design_1_Register_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
